import os
import json
from PIL import Image, ExifTags

def extract_metadata(file_path):
    """
    Extracts basic image metadata, EXIF data, and analyzes it for AI/editing signatures.
    """
    metadata = {
        "filename": os.path.basename(file_path),
        "size_bytes": os.path.getsize(file_path),
        "format": None,
        "dimensions": None,
        "mode": None,
        "exif": {},
        "raw_info": {},
        "analysis": {
            "red_flags": [],
            "detections": [],
            "camera_info": {
                "make": None,
                "model": None,
                "lens": None,
                "iso": None,
                "exposure": None
            },
            "software": None,
            "has_gps": False
        }
    }
    
    try:
        with Image.open(file_path) as img:
            metadata["format"] = img.format
            metadata["dimensions"] = f"{img.width}x{img.height}"
            metadata["mode"] = img.mode
            
            # Extract info dictionary (useful for PNGs and general metadata)
            for k, v in img.info.items():
                if isinstance(v, bytes):
                    try:
                        v = v.decode('utf-8')
                    except UnicodeDecodeError:
                        v = str(v)
                if len(str(v)) < 1000: # Increase limit to catch SD prompts
                    metadata["raw_info"][str(k)] = str(v)

            # Extract EXIF
            exif_data = img.getexif()
            if hasattr(img, '_getexif') and img._getexif():
                exif_data = img._getexif()
                
            if exif_data:
                for tag_id, value in exif_data.items():
                    tag = ExifTags.TAGS.get(tag_id, tag_id)
                    
                    if isinstance(value, bytes):
                        try:
                            value = value.decode('utf-8')
                        except UnicodeDecodeError:
                            value = str(value)
                    
                    if len(str(value)) < 500:
                        metadata["exif"][str(tag)] = str(value)
                        
                        # Populate camera info
                        tag_str = str(tag).lower()
                        if tag_str == 'make':
                            metadata["analysis"]["camera_info"]["make"] = str(value)
                        elif tag_str == 'model':
                            metadata["analysis"]["camera_info"]["model"] = str(value)
                        elif tag_str == 'lensmodel':
                            metadata["analysis"]["camera_info"]["lens"] = str(value)
                        elif tag_str == 'isospeedratings':
                            metadata["analysis"]["camera_info"]["iso"] = str(value)
                        elif tag_str == 'exposuretime':
                            metadata["analysis"]["camera_info"]["exposure"] = str(value)
                        elif tag_str == 'software':
                            metadata["analysis"]["software"] = str(value)
                        elif tag_str == 'gpsinfo':
                            metadata["analysis"]["has_gps"] = True

            # Analysis Logic
            red_flags = metadata["analysis"]["red_flags"]
            detections = metadata["analysis"]["detections"]
            
            exif_empty = not metadata["exif"]
            has_camera = metadata["analysis"]["camera_info"]["model"] is not None
            software = metadata["analysis"]["software"] or metadata["raw_info"].get("Software", "")
            
            # Combine all text data to search for signatures
            all_text_data = json.dumps(metadata["exif"]) + json.dumps(metadata["raw_info"])
            all_text_lower = all_text_data.lower()

            # 1. Check for missing metadata
            if exif_empty and metadata["format"] in ["JPEG", "TIFF"]:
                red_flags.append("Metadata stripped or completely missing")
                detections.append("Metadata stripped")
                
            if not has_camera and not exif_empty:
                red_flags.append("Missing Camera Model/Make in EXIF")

            # 2. Check for Generator Tags
            ai_signatures = {
                "stable diffusion": "Generated by Stable Diffusion",
                "midjourney": "Generated by Midjourney",
                "dall-e": "Generated by DALL-E",
                "comfyui": "Generated using ComfyUI",
                "fooocus": "Generated using Fooocus",
                "novelai": "Generated by NovelAI"
            }
            
            for sig, detection in ai_signatures.items():
                if sig in all_text_lower:
                    red_flags.append(f"Found AI generator tag: {sig}")
                    if detection not in detections:
                        detections.append(detection)
                        
            # PNG specific checks for Stable Diffusion parameters
            if "parameters" in metadata["raw_info"] and "Steps:" in metadata["raw_info"]["parameters"]:
                red_flags.append("Found Stable Diffusion generation parameters")
                if "Generated by Stable Diffusion" not in detections:
                    detections.append("Generated by Stable Diffusion")

            # 3. Editing Software
            if software:
                software_lower = software.lower()
                if "photoshop" in software_lower or "adobe" in software_lower:
                    red_flags.append("Image was edited in Photoshop/Adobe software")
                    detections.append("Photoshop AI edit / manipulation")
                elif "gimp" in software_lower:
                    red_flags.append("Image was edited in GIMP")
                elif "lightroom" in software_lower:
                    red_flags.append("Image processed in Lightroom")
            
            # Additional Adobe XMP checks
            if "adobe" in all_text_lower and "photoshop" not in str(software).lower():
                red_flags.append("Adobe XMP metadata found")
                if "Photoshop AI edit / manipulation" not in detections:
                    detections.append("Photoshop AI edit / manipulation")

            # 4. Metadata Inconsistency
            if software and has_camera:
                red_flags.append(f"Camera photo modified by software: {software}")

    except Exception as e:
        print(f"Error extracting metadata: {e}")
        
    return metadata
